[package]
name = "e-melder-gui"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
eframe = { version = "0.26.2", features = ["wgpu"] }
egui = { version = "0.26.2", features = ["accesskit"] }
egui_extras = { version = "0.26.2", features = ["chrono"] }
home = "0.5.9"
serde_json = "1.0.114"

[features]
debugging = []
